# Generated by Django 4.2.3 on 2023-07-28 10:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Publish')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('image', models.ImageField(upload_to='image', verbose_name='Image')),
                ('caption', models.TextField(verbose_name='Caption')),
                ('is_published', models.BooleanField(default=True, help_text='Public Ads will be displayed in the api views.', verbose_name='Is Published')),
                ('publisher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='Publisher')),
            ],
            options={
                'verbose_name': 'ad',
                'verbose_name_plural': 'ads',
                'ordering': ('-date_added',),
                'get_latest_by': 'date_added',
            },
        ),
    ]
